export const services = [
  {
    id: 1,
    title: "Scrap Dealing",
    description: "Sell your scrap materials at best prices",
    icon: "recycle",
    color: "#4CAF50",
    items: [
      { id: 1, name: "Iron & Steel", price: "₹25-30/kg", category: "Metal" },
      { id: 2, name: "Aluminum", price: "₹120-140/kg", category: "Metal" },
      { id: 3, name: "Copper", price: "₹450-500/kg", category: "Metal" },
      { id: 4, name: "Brass", price: "₹280-320/kg", category: "Metal" },
      { id: 5, name: "Newspaper", price: "₹8-12/kg", category: "Paper" },
      { id: 6, name: "Cardboard", price: "₹6-10/kg", category: "Paper" },
      { id: 7, name: "Plastic Bottles", price: "₹15-20/kg", category: "Plastic" },
      { id: 8, name: "Car Battery", price: "₹80-120/piece", category: "Battery" },
    ],
  },
  {
    id: 2,
    title: "E-Waste Services",
    description: "Safe disposal of electronic waste",
    icon: "phone-portrait",
    color: "#2196F3",
    items: [
      { id: 9, name: "Desktop Computer", price: "₹500-800/piece", category: "Computer" },
      { id: 10, name: "Laptop", price: "₹300-600/piece", category: "Computer" },
      { id: 11, name: "Smartphone", price: "₹100-300/piece", category: "Mobile" },
      { id: 12, name: "Tablet", price: "₹200-400/piece", category: "Mobile" },
      { id: 13, name: "LED TV", price: "₹800-1500/piece", category: "Appliance" },
      { id: 14, name: "Refrigerator", price: "₹1000-2000/piece", category: "Appliance" },
      { id: 15, name: "Printer", price: "₹200-500/piece", category: "Office" },
      { id: 16, name: "UPS Battery", price: "₹50-100/piece", category: "Battery" },
    ],
  },
  {
    id: 3,
    title: "Demolition Services",
    description: "Professional demolition services",
    icon: "hammer",
    color: "#FF9800",
    items: [
      { id: 17, name: "Residential Demolition", price: "Quote on Request", category: "Residential" },
      { id: 18, name: "Commercial Demolition", price: "Quote on Request", category: "Commercial" },
      { id: 19, name: "Industrial Demolition", price: "Quote on Request", category: "Industrial" },
      { id: 20, name: "Selective Demolition", price: "Quote on Request", category: "Selective" },
      { id: 21, name: "Concrete Breaking", price: "₹50-80/sq ft", category: "Concrete" },
      { id: 22, name: "Wall Removal", price: "₹30-50/sq ft", category: "Wall" },
    ],
  },
  {
    id: 4,
    title: "Facility Decommissioning",
    description: "Complete facility shutdown solutions",
    icon: "business",
    color: "#9C27B0",
    items: [
      { id: 23, name: "Asset Inventory", price: "Quote on Request", category: "Assessment" },
      { id: 24, name: "Equipment Removal", price: "Quote on Request", category: "Removal" },
      { id: 25, name: "Environmental Cleanup", price: "Quote on Request", category: "Cleanup" },
      { id: 26, name: "Site Restoration", price: "Quote on Request", category: "Restoration" },
    ],
  },
  {
    id: 5,
    title: "Recycling Services",
    description: "Transform waste into valuable resources",
    icon: "leaf",
    color: "#8BC34A",
    items: [
      { id: 27, name: "Paper Recycling", price: "₹8-15/kg", category: "Paper" },
      { id: 28, name: "Plastic Recycling", price: "₹12-25/kg", category: "Plastic" },
      { id: 29, name: "Glass Recycling", price: "₹5-10/kg", category: "Glass" },
      { id: 30, name: "Metal Recycling", price: "₹20-500/kg", category: "Metal" },
      { id: 31, name: "Organic Waste", price: "₹2-5/kg", category: "Organic" },
      { id: 32, name: "Textile Recycling", price: "₹8-15/kg", category: "Textile" },
    ],
  },
] 